ghomes.languages = {}
ghomes.languages.fr  = 1;
ghomes.languages.en  = 2;


function ghomes.picklanguage(_language)
	if not _language then _language = ghomes.languages.en end
	if not ghomes.languages.table[_language] then _language = ghomes.languages.en  end
	table.Merge(ghomes,ghomes.languages.table[_language])
	ghomes.languages.currentLang = _language
end


ghomes.languages.table = --best syntax ever
{
	{
		purchaseprice = "Prix d'achat : ",
		rentalprice = "Prix de la location : ",
		pricepropertysize = "Le prix est basé sur la taille de la propriété (x*y*z)",
		sliderchangeprice = "Le slider permet de changer le prix au m²",
		leasingpurchase = "Location + Achat",
		purchasesonly = "Achat seulement",
		leasingonly = "Location seulement",
		perdays = " par jour",
		purchasefor = "Acheter %s pour %s.",
		renthomefordays = "Louer %s %i jours pour %s",
		renthomeforhours = "Louer %s %i heures pour %s",
		numberofdays = "Nombre de jours : %i",
		numberofhours = "Nombre d'heures : %i",
		purchase = "Acheter",
		rent = "Louer",
		purchaserent = "Acheter/Louer",
		confirmsell1 = "Êtes vous sûr de vouloir vendre %s pour %s (%i%% du prix original)",
		confirmbreaklease = "Êtes vous sûr de vouloir rompre le bail ?\n\nVous ne récupérerez pas votre argent",

		managebuddies = "Liste d'amis",
		buddiestitle = "Gérer la liste d'amis",
		buddiestitle2 = "Joueurs sur le serveur",
		buddiestitle3 = "Joueurs dans votre liste d'amis",
		buddiestitlego = "Envoyer la liste",

		renewleasetext = "Si vous décidez de renouvelez le bail, vous n'aurez pas de\nfrais additionnel.\nNéanmoins, vous perdrez les jours restant sur le bail actuel.",
		numberofdays2 = "Nombre de jours : ",
		numberofhours2 = "Nombre d'heures : ",
		itwillcostyou = "Cela vous coûtera %s pour %i jour(s).",
		itwillcostyouhour = "Cela vous coûtera %s pour %i heure(s).",
		realestateagent = "Agent immobilier",
		information = "Information",
		status = "Statut",
		actions = "Action",
		previewofhome = "Aperçu du foyer",
		purchaseprice2 = "Prix d'achat : %s",
		dailypricerental = "Prix journalier : %s",
		numberofdoors = "Nombre de portes : %i",
		heightm = "Hauteur : %im",
		lengthm = "Longueur : %im",
		widthm = "Largeur : %im",
		notavailable = "Non disponible",
		coowned = "Locataire",
		coowners = "Co-Propriétaires",
		owned = "Acquis",
		buy = "Acheter",
		clearoff = "Déménager",
		friends = "Amis",
		preview = "Aperçu",
		msgwroteby = "Mail écrit par by : %s",
		writingamsg = "Écriture d'un mail",
		recipient = "Destinataire : ",
		typemessagehere = "Écrivez votre message ici",
		leaseexpiresin = "Le bail expire dans %s",
		leasehasexpired = "Le bail a expiré.",
		ringthebell = "Sonnette",
		readmail = "Mails",
		leaveamessage = "Laisser un message",
		renewthelease = "Renouveler bail",
		sellthehome = "Vendre le foyer",
		breakthelease = "Rompre le bail",
		vacant2 = " : Libre",
		owned2 = " : Occupé",
		rented2 = " : Loué",
		priceorperday = "Prix : %s ou %s par jour",
		priceorperday2 = "Prix : %s",
		priceorperday3 = "Prix : %s par jour",
		sperday = "%s par jour",
		sperhour = "%s par heure",
		oronlysperday = "Ou seulement %s par jour",
		unitday = "jour",
		unithour = "heure",
		unitminute = "minute",
		unitsecond = "seconde",
		evict = "Expulser",
		settings = "Options",
		nextpage = "Suivant",
		prevpage = "Précédent",
		youdontownany = "Vous n'avez n'avez/ne louez aucune propriété, procurez-vous en une d’abord.",
		welcomehome = "Bon retour chez vous, vous nous avez manqué !",
		spawnhomeowner = "Apparition içi (Sauf si policier)",
		spawnhomefriends = "Apparition içi pour co-proprios (Sauf si policier)",
		saveentities = "Sauvegarder certaines entités (Printers par exemple)",
		buyalarm =  Format("Alarme anti-intrusions (%i€)", ghomes.alarmprice),
		beingrobbed = "Votre maison : %s est en train de se faire cambrioler ! Appelez la police !",
		chooseWhereToRespawn = "Choisissez où apparaître.",
		rememberChoiceForThisSession = "Se rappeler du choix pour la session. (Remis à zéro si échec)",
		defaultSpawn = "Zone d'apparition par défaut."

	},
	{
		purchaseprice = "Purchase price : ",
		rentalprice = "Rental price : ",
		pricepropertysize = "The price is based on the size of the property (x*y*z)",
		sliderchangeprice = "The slider allows you to change the price per square meter",
		leasingpurchase = "Leasing + Purchase",
		purchasesonly = "Purchase Only",
		leasingonly = "Leasing Only",
		perdays = " per day",
		purchasefor = "Purchase %s for %s.",
		renthomefordays = "Rent %s %i day for %s",
		renthomeforhours = "Rent %s %i hours for %s",
		numberofdays = "Number of days : %i",
		numberofhours = "Number of hours : %i",
		purchase = "Purchase",
		rent = "Rent",
		purchaserent = "Purchase/Rent",
		confirmsell1 = "Are you sure you want to sell %s for %s (%i%% of the original price)",
		confirmbreaklease = "Are you sure you want to break the lease agreement ?\n\nYou will NOT get your money back",

		managebuddies = "Manage buddies",
		buddiestitle = "Manage Buddy list",
		buddiestitle2 = "Players connected on the server",
		buddiestitle3 = "Players in your Buddy list",
		buddiestitlego = "Send updated list",

		renewleasetext = "If you decide to renew the lease now, you will not have\nadditional fees.\nHowever, you will lose every day remaining on your lease.",
		numberofdays2 = "Number of days : ",
		numberofhours2 = "Number of hours : ",
		itwillcostyou = "It will cost you %s for %i day(s).",
		itwillcostyouhour = "It will cost you %s for %i hour(s).",
		realestateagent = "Real estate agent",
		information = "Information",
		status = "Status",
		actions = "Action",
		previewofhome = "Preview of the home",
		purchaseprice2 = "Purchase price : %s",
		dailypricerental = "Daily price (Rental) : %s",
		numberofdoors = "Number of doors : %i",
		heightm = "Height : %im",
		lengthm = "Length : %im",
		widthm = "Width : %im",
		notavailable = "Not Available",
		coowned = "Co-Owned",
		coowners = "Co-Owners",
		owned = "Owned",
		buy = "Buy",
		clearoff = "Clear Off",
		friends = "Friends",
		preview = "Preview",
		msgwroteby = "Message wrote by : %s",
		writingamsg = "Writing a message",
		recipient = "Recipient : ",
		typemessagehere = "Type your message here",
		leaseexpiresin = "Lease expires in %s",
		leasehasexpired = "The lease has expired.",
		ringthebell = "Ring the doorbell",
		readmail = "Read Mail",
		leaveamessage = "Leave a message",
		renewthelease = "Renew the lease",
		sellthehome = "Sell the home",
		breakthelease = "Break the lease",
		vacant2 = " : Vacant",
		owned2 = " : Owned",
		rented2 = " : Rented",
		priceorperday = "Price : %s or %s per day",
		priceorperday2 = "Price : %s",
		priceorperday3 = "Price : %s per day",
		sperday = "%s per day",
		sperhour = "%s per hour",
		oronlysperday = "Or only %s per day",
		unitday = "day",
		unithour = "hour",
		unitminute = "minute",
		unitsecond = "second";
		evict = "Evict",
		settings = "Settings",
		nextpage = "Next",
		prevpage = "Previous",
		youdontownany = "You aren't owning/renting any property, get one first.",
		welcomehome = "Welcome home, we missed you !",
		spawnhomeowner = "Spawn here (unless you're a cop)",
		spawnhomefriends = "Co-owners spawns here (unless working in the police)",
		saveentities = "Save some of the entities (money printers for example)",
		buyalarm = Format("Anti-Burglar Alarm System ($%i)", ghomes.alarmprice),
		beingrobbed = "Your house : %s is being robbed! Call the police!",
		chooseWhereToRespawn = "Choose where to respawn.",
		rememberChoiceForThisSession = "Remember choice for this session. (Reset if failure)",
		defaultSpawn = "Default spawn location."

	}
}
